//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mail_Phishing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplate
    {
        public int Id { get; set; }
        public string MailSubject { get; set; }
        public string MailBody { get; set; }
    }
}
